coach_names = [
    "Bill Belichick", "Andy Reid", "Mike Tomlin", "Kyle Shanahan", "Sean McVay",
    "John Harbaugh", "Pete Carroll", "Matt LaFleur", "Doug Pederson", "Sean Payton",
    "Mike McCarthy", "Dan Campbell", "Kevin Stefanski", "Zac Taylor", "Nick Sirianni",
    "Brian Daboll", "Mike Vrabel", "Ron Rivera", "Dennis Allen", "Robert Saleh",
    "Erik Spoelstra", "Steve Kerr", "Gregg Popovich", "Michael Malone", "Ime Udoka",
    "Joe Mazzulla", "Tyronn Lue", "Darvin Ham", "Tom Thibodeau", "Nick Nurse",
    "Monty Williams", "Will Hardy", "Chris Finch", "Quin Snyder", "Taylor Jenkins",
    "Rick Carlisle", "Chauncey Billups", "Steve Clifford", "Mark Daigneault", "Jason Kidd",
    "Dusty Baker", "Torey Lovullo", "Brian Snitker", "Dave Roberts", "Bruce Bochy",
    "Aaron Boone", "Buck Showalter", "Kevin Cash", "Gabe Kapler", "Scott Servais",
    "Bob Melvin", "Alex Cora", "Oliver Marmol", "Rocco Baldelli", "Terry Francona",
    "David Ross", "AJ Hinch", "Craig Counsell", "Pedro Grifol", "Brandon Hyde",
    "Jon Cooper", "Rod Brind’Amour", "Peter DeBoer", "Mike Sullivan", "Darryl Sutter",
    "Jared Bednar", "Sheldon Keefe", "Bruce Cassidy", "Dean Evason", "Todd McLellan",
    "D.J. Smith", "Paul Maurice", "Gerard Gallant", "Rick Bowness", "John Tortorella",
    "Lindy Ruff", "Andrew Brunette", "Lane Lambert", "Derek Lalonde", "David Quinn",
    "Bruce Arena", "Jim Curtin", "Wilfried Nancy", "Brian Schmetzer", "Greg Vanney",
    "Phil Neville", "Gonzalo Pineda", "Pat Noonan", "Josh Wolff", "Steve Cherundolo",
    "Robin Fraser", "Luchi Gonzalez", "Oscar Pareja", "Peter Vermes", "Adrian Heath",
    "Pep Guardiola", "Jürgen Klopp", "Mikel Arteta", "Carlo Ancelotti", "Diego Simeone",
    "Mauricio Pochettino", "Thomas Tuchel", "Luis Enrique", "Roberto Mancini", "Erik ten Hag",
    "Alfred Carter", "Ben Holloway", "Charlie Vickers", "Dexter Reid", "Elliot Grant",
    "Franklin Bowen", "Gordon Nash", "Howard Fraser", "Irving Shaw", "Jonah Blake",
    "Kenneth Palmer", "Lloyd Duncan", "Marcus Harlow", "Nelson Harper", "Oscar Newton",
    "Patrick Glenn", "Quincy Moore", "Ralph Dixon", "Spencer Hayes", "Terry Lloyd",
    "Victor Crane", "Wallace Garrison", "Xavier Frost", "Yale Morton", "Zachary Monroe",
    "Aaron Miles", "Barrett Stone", "Chandler Knox", "Damon Woods", "Edgar Pierce",
    "Fletcher Wells", "Garrison Holt", "Harvey McCoy", "Isaiah Booker", "Jared Thornton",
    "Kendall Owens", "Lamar Briggs", "Mitchell Vaughn", "Nathaniel Perry", "Oliver Tate",
    "Preston Carter", "Quentin Browne", "Reed Douglas", "Silas Murray", "Tobias Hart",
    "Ulysses Ford", "Vince Wheeler", "Wayne Armstrong", "Xander Cole", "Yates Hampton",
    "Zane Conner", "Alton Hayes", "Brody Mitchell", "Cameron Doyle", "Declan Murphy",
    "Ezekiel McBride", "Felix Rodgers", "Graham Fuller", "Harrison Drake", "Ivan Steele",
    "Jackson Ellis", "Kirk Abbott", "Landon Harris", "Marshall Greer", "Noah Chambers",
    "Orlando Gibbs", "Phillip Brock", "Randall Briggs", "Simon Bell", "Trevor Hensley",
    "Urban Wilkes", "Vincent Corbin", "Wade Nelson", "Xavier Dalton", "Yosef Pratt",
    "Zeke Collins", "Alan Parker", "Bennett Tucker", "Collin Hunter", "Donovan Barrett",
    "Everett Hayes", "Foster Sharp", "Grady Monroe", "Hudson Collins", "Isaac Webster",
    "Julian Frost", "Kyle Spencer", "Leland Monroe", "Miles Griffith", "Nelson Price",
    "Otis Grant", "Porter Hayes", "Quentin Foster", "Riley Buchanan", "Shane Baxter",
    "Trenton Stone", "Uriah Davis", "Victor Hart", "Wesley Payne", "Xander Morris",
    "Yusuf Kent", "Zion Bishop", "Arnold Perry", "Blake Conrad", "Clyde Monroe",
    "Dallas Fuller", "Edmund Holt", "Finley Graham", "Grant Booker", "Harvey Taylor",
    "Irving Knox", "Jameson Blake", "Kirk Douglas", "Logan Price", "Mason Kent",
    "Nolan Craig", "Orin Crawford", "Preston Drake", "Quinn Tucker", "Ross Palmer",
    "Spencer Sharp", "Travis Garrison", "Ulrich Foster", "Victor Parker", "Wayne Briggs",
    "Xander Bishop", "Yates Crawford", "Zane Wilkins", "Arthur Hughes", "Bryce Fuller",
    "Carter Hensley", "Derek Vaughn", "Elijah Monroe", "Finn Dawson", "Garrett Woods"
]

extra_first_names = [
    "Michael", "Serena", "Tiger", "Cristiano", "Lionel", "Tom", "Roger", "Usain",
    "Kobe", "Simone", "Stephen", "Kevin", "Shaquille", "Derek", "Wayne", "Novak", "Rafael",
    "Giannis", "Lewis", "Megan", "Alex", "Patrick", "Kareem", "Wilt", "Naomi", "Venus",
    "Luka", "Nikola", "Dirk", "Tim", "Larry", "Magic", "Zlatan", "David", "Pelé", "Diego",
    "Bill", "Joe", "Aaron", "Babe", "Jackie", "Sidney", "Bobby", "Mario", "Arsène", "Pep",
    "Jurgen", "Phil", "Gregg", "Steve", "Pat", "Tony", "Vince", "Andy", "Jimmie", "Dale",
    "Kyle", "Sebastian", "Fernando", "Max", "Alain", "Niki", "Bruce", "Dan", "John", "Paul",
    "Randy", "Terry", "Doug", "Oscar", "Yogi", "Reggie", "Bo", "Julius", "Allen",
    "Dwight", "Hakeem", "Tracy", "Grant", "Ray", "Chris", "Dominique", "Isiah", "Russell"
]

extra_last_names = [
    "Smith", "Johnson", "Brown", "Taylor", "Anderson", "Thomas", "Jackson",
    "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson",
    "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young",
    "King", "Wright", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson",
    "Carter", "Mitchell", "Perez", "Roberts", "Turner", "Phillips", "Campbell",
    "Parker", "Evans", "Edwards", "Collins", "Stewart", "Sanchez", "Morris",
    "Rogers", "Reed", "Cook", "Morgan", "Bell", "Stratus", "Bishop", "Benn"
]

team_names = ["Phoenixes", "Dragons", "Banshees", "Wraiths", "Revenants", "Seraphs", "Chimera",
              "Gorgons",
              "Minotaurs", "Harpies", "Mermaids", "Naga", "Satyrs", "Centaur", "Unicorns", "Griffins", "Rocs",
              "Sphinxes", "Cyclops", "Titans", "Fates", "Valkyries", "Demigods", "Godkillers", "Inferno", "Hive",
              "Elementals", "Golems",
              "Ifrits", "Djinni", "Imps", "Sprites", "Goblins", "Trolls", "Orcs", "Zombies", "Ghosts", "Werewolves",
              "Vampires", "Liches", "Slayers", "Faeries", "Elves", "Dwarves", "Gnomes",
              "Halflings", "Ogres", "Hydra", "Kraken", "Leviathan", "Serpents", "Basilisks", "Wendigo",
              "Wyverns", "Behemoths", "Manticore", "Naiads", "Frostlords", "Ghost-Runners", "Ents", "Terraformers",
              "Dryads", "Sirens", "Eladrin", "Draconians", "Demons", "Angelkin", "Succubi", "Incubi", "Nebulae",
              "Oni", "Kitsune", "Rakshasa", "Feykin", "Impalers", "Necromancers", "Warlocks", "Lunatics",
              "Enchanters", "Shamans", "Sorcerers", "Illusionists", "Geomancers", "Chronomancers", "Aether",
              "Diviners", "Magi", "Alchemists", "Witchdoctors", "Arcanists", "Summoners", "Zealots", "Thunderbirds",
              "Purifiers", "Exorcists", "Warden", "Guardians", "Protectors", "Crusaders", "Paladins", "Armament",
              "Gravity", "Assassins",
              "Templars", "Inquisitors", "Acolytes", "Clerics", "Priests", "Druids", "Shapeshifters", "Skinwalkers",
              "Warg", "Beastmasters", "Dervish", "Puppeteer", "Psychic", "Oracle", "Mystic", "Tar-Creepers",
              "Amalgam", 'Wings', 'Termites', 'Revolution',
              'Arch-Kings', 'Samurai', 'Darkness', 'Voidwalkers', 'Ghasts', 'Watchers', 'Bloodspawn',
              'Night-Terrors', 'Underlords', 'Devils',
              'Swashbucklers', 'Sunspots', "Aces", "Red-Specters", "Rangers", "Ironclads", "Vortex",
              "Stormbringers", "Skypiercers",
              "Patriots", "Lakers", "Yankees", "Packers", "Cowboys", "Bulls", "Steelers",
              "Celtics", "Red-Sox", "Raiders", "Braves", "Giants", "Penguins", "Mariners",
              "Knicks", "Avalanche", "Rockets", "Twins", "Royals", "Cardinals", "Bengals", "Raptors", "Ducks",
              "Grizzlies", "Fangs", "Eagles", "Blizzards", "Stormhawks", "Thunderbolts", "Blackjacks", "Redwolves",
              "Firebirds",
              "Shadowhunters", "Silverbacks", "Bluehawks", "Hurricanes", "Sandstorm", "Frostfangs", "Icebreakers",
              "Nightmares", "Bladesmiths", "Skullcrushers", "Wildcats", "Mountain-Lions", "Cougars", "Bobcats",
              "Lightning",
              "Polar-Bears", "Ravagers", "Outlaws", "Nomads", "Marauders", "Stone-Giants",
              "Sunseekers", "Lunarians", "Radiants", "Spectrals", "Oblivion", "Hellhounds", "Blaze", "Fury",
              "Crusaders",
              "Stormriders", "Apex", "Wolfpack", "Lynx", "Savages", "Predators", "Tempest", "Eclipse", "Shockwave",
              "Volcanos", "Fever", "Mavericks"
              ]

player_names = [
  "Aria", "Ashton", "Amara", "Ari", "Anya",
  "Bryce", "Brennan", "Briar", "Brodie",
  "Calla", "Cameron", "Carson", "Cassius", "Chase",
  "Dakota", "Darcy", "Dallas", "Darian", "Devin",
  "Ellis", "Elliott", "Emery", "Eris", "Evelyn",
  "Finley", "Flynn", "Finnegan", "Felicity", "Freya",
  "Gia", "Gael", "Gwen", "Gunnar", "Giselle",
  "Harlow", "Harper", "Hayden", "Hadley", "Hunter",
  "Iris", "Indiana", "Isadora", "Isla", "Imogen",
  "Jude", "Jordan", "Jax", "Jasper", "Jocelyn",
  "Kai", "Carter", "Keegan", "Kendall", "Kyra",
  "Lennon", "Linden", "Landon", "Logan", "Lorelei",
  "Madden", "Marley", "Maddox", "Mason", "Mila",
  "Nova", "Nash", "Nico", "Nolan", "Naya",
  "Oakley", "Odessa", "Orion", "Oliver", "Ophelia",
  "Parker", "Phoenix", "Presley", "Paxton", "Primrose",
  "Quinn", "Quincy", "Quest", "Queenie", "Quinten",
  "Rowan", "Reagan", "Reeve", "Raven", "Ryder",
  "Sage", "Sawyer", "Saylor", "Sutton", "Sparrow",
  "Tatum", "Tanner", "Tate", "Theo", "Tilly",
  "Urban", "Uriel", "Ulysses", "Umberto", "Una",
  "Vesper", "Vida", "Valentine", "Vance", "Verity",
  "Wren", "Weston", "Willow", "Wilder", "Winslow",
  "Xanthe", "Xander", "Ximena", "Xiomara", "Xena",
  "Yara", "Yasmine", "Yael", "Yvette", "Yvonne",
  "Zephyr", "Zara", "Zander", "Zeke", "Zelda", "Zain",
    "Killer", "Zoro", "Luffy", "Brook", "Nami"
]